title: "secStudy"
url: "https://discord.gg/cyZeBsSG"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  
author:
  name: "luz4r"
  github: "github.com/luz4rr"


minima:
skin: solarized

exclude:
  - README.md
