theme: minima

author:
name: "luz4r"
github: "github.com/luz4rr"

url: "https://discord.gg/cyZeBsSG"

plugins:
-jekyll-feed
- jekyll-seo-tag
- jukyll-sitemap

minima:
skin: solarized

exclude:
  - README.md
