theme: minima

author:
  name: "luz4r"
  github: "github.com/luz4rr"

url: "https://luz4rr.github.io/secstudy/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jukyll-sitemap

minima:
  skin: solarized
  social_links:
    discord: https://discord.gg/cyZeBsSG

exclude:
  - README.md
